CommitMsg:
  AddTicketId:
    enabled: true

PreCommit:
  DartAnalyzer:
    enabled: true
    description: 'Analyze with DartAnalzer'
    required_executable: 'dartanalyzer'
    # TODO remove once DartAnalyzer is merged and released
    # https://github.com/sds/overcommit/pull/739
    flags: ['.']
    include: '**/*.dart'

PrePush:
  # TODO change to FlutterTest once https://github.com/sds/overcommit/pull/740 is merged and released
  # Since most pre_push hooks in overcommit do the same thing , this will not be an issue
  # (FlutterTest will do the same as TestUnit just using different configuration)
  #
  # Using preexisting name instead of custom hook prevents passing default args to command
  # Which would in case of pre-push be name and URL of remote
  TestUnit:
    enabled: true
    description: 'Run flutter test suite'
    required_executable: 'flutter'
    # TODO remove when changed to FlutterTest
    command: ['flutter', 'test']
    flags: ['test']

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes

verify_signatures: false
