# Flutter lint config file
include: package:pedantic/analysis_options.yaml

# Disable specific rules
# Since `flutter analyze` has issues,
# it is possible some rules will have to be ignored
# (https://github.com/flutter/flutter/issues/20855)
# linter:
#   rules:
