name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        # we want the latest Java 12
        java-version: '12.x'
    # Use the community Action to install Flutter
    - name: Prepare flutter environment
      uses: subosito/flutter-action@v1
      with:
        # we want the stable channel
        channel: 'stable'
    - name: Install Dependencies
      run: flutter pub get
    - name: Flutter Analyze
      run: flutter analyze --no-pub
    - name: Check Flutter Formatting
      run: flutter format lib/** --set-exit-if-changed
    - name: Run Flutter Tests
      run: flutter test --no-pub
